### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by khwerhahn** [hypriot/flash#104]
I  tried to install on mac by just copy & paste the following command:
`curl -O https://raw.githubusercontent.com/hypriot/flash/master/$(uname -s)/flash`
Result:
![screen shot 2017-09-20 at 19 55 24](https://user-images.githubusercontent.com/3821617/30659310-b39df472-9e3d-11e7-95ec-1fe5830434e7.png)

**Comment by firecyberice** [comment]
You have escaped the `(` in your screenshot `$\(uname -s)` instead of `$(uname -s)`.
