### ISSUE TITLE
Request:  Use mac address of boot device for host name

### ISSUE THREAD

**Issue by jmulvaney1** [hypriot/flash#105]
Any way that I can pass the mac address of the boot device to become the host name during first boot?  MAC+fixed named.

**Comment by StefanScherer** [comment]
Maybe this could be done with some script commands in the `/boot/user-data` file for the cloud-init run on first boot. But it's not part of the flash tool itself.

**Comment by StefanScherer** [comment]
Maybe you find some inspiration in https://cloudinit.readthedocs.io/en/latest/
