### ISSUE TITLE
Cache OS downloads?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [hypriot/flash#123]
Love the http syntax, but does it download fresh every time? Could it use LastModified or ETAGs or some other http technique to avoid downloading the second time, and use local copy?

**Comment by GeoffreyPlitt** [comment]
Shoot, I should have noticed that-- it sounds great, nothing more needed!

**Comment by GeoffreyPlitt** [comment]
Actually, the /tmp cache doesn't seem to be working.

I just flashed a Pi successfully with ```sudo flash --force https://downloads.raspberrypi.org/raspbian_lite_latest```

Inserted a new card, did it again, it downloaded the OS again instead of using /tmp.

Thoughts?

**Comment by StefanScherer** [comment]
The simple cache doesn't work with download links that use a different name than the extracted img file. Look inside /tmp.
You can use that /tmp/xxxx name for further flashes or send me a PR to fix it :-)

**Comment by GeoffreyPlitt** [comment]
Oh duh. I can use a more specific URL, the one above is likely a redirect. Thanks again.
