### ISSUE TITLE
Donation page cannot access from Tokyo

### ISSUE THREAD

**Issue by sinpaout** [hypriot/flash#127]
## Screenshot

![screencapture-liberapay-hypriot-donate-2018-06-03-12_04_41](https://user-images.githubusercontent.com/10008699/40882740-5e2b8038-6726-11e8-9e19-667d9dfdd39a.png)

**Comment by StefanScherer** [comment]
Thanks @sinpaout 
Unfortunetely I can see the problem here in Germany, too.

**Comment by StefanScherer** [comment]
The site is back online.
