### ISSUE TITLE
This command can only be used by root.

### ISSUE THREAD

**Issue by exocode** [hypriot/flash#137]
Hi there, I did not know in which repo I should post that.... 

I tried to install Kubernetes onto my HypriotOS RPI Zero. Kubernetes is only installable via "root" user. But HypriotOS dont provide a root user. 

I followed the example by google/kubernetes Blog which also supports the HypriotOS, but it seems outdated -> `https://kubernetes.io/docs/setup/independent/install-kubeadm/#before-you-begin`

I stuck on this part:

`curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -`
Error: `E: This command can only be used by root.`

How do I perform progress?

**Comment by exocode** [comment]
found a way::

https://blog.hypriot.com/post/setup-kubernetes-raspberry-pi-cluster/

**Comment by StefanScherer** [comment]
@exocode Glad you found the blog post.
I didn't know that we are mentioned in the kubernetes docs :-)
All these steps there require root access, so you need `sudo` or just make you root with `sudo su` and then type the commands.

**Comment by exocode** [comment]
@StefanScherer next problem: It seems that kubernetes dropped support for ARM or some kind of.. 
I got this `illegal instruction` error when using `kubeadm`.
They suggest to downgrade to `<= 1.5.1` of kubernetes, but who likes to play with old software... 
Now I investigating.. 
https://github.com/kubernetes/kubeadm/issues/253#issuecomment-296738890

**Comment by StefanScherer** [comment]
They dropped RPi 1 support, so a Pi 2 or 3 should work. 
But I never spun up a Kubernetes cluster on ARM yet so I don‘t know more details what might be the problem.
