### ISSUE TITLE
hypriot flash: line 150 syntax error

### ISSUE THREAD

**Issue by kenpeter** [hypriot/flash#14]
https://github.com/hypriot/flash/blob/master/Linux/flash#L150

On Linux, I need to change 
if [[ `echo "${disk}"|awk '{print NF}'` -gt 1 ]]; then

to

if [[ `echo "${disk}"|awk '{print NF}'` > 1 ]]; then

**Comment by StefanScherer** [comment]
A greater sign does not really fix the problem, it just redirects the output of echo into a file `1`.
Any other Linux user out there to help here?

**Comment by StefanScherer** [comment]
I'll close this one due to inactivity.
