### ISSUE TITLE
Set fake-hwclock to current date

### ISSUE THREAD

**Issue by Legion2** [hypriot/flash#151]
Raspberry Pi only have a fake hwclock. It's used on boot and shutdown to get and save the "current" date. But the fake-hwclock is only updated while the Pi is running and so on first boot the date is usually very far in the past (the date when the image was created). To fix this, the fake-hwclock data file `/etc/fake-hwclock.data` should be updated when the image is flashed on the sd card. This will minimize the offset of the `fake-hwclock` on first boot.

This will most likely also fix hypriot/image-builder-rpi#304.

**Comment by StefanScherer** [comment]
Fixed with #162
