### ISSUE TITLE
maintain a homebrew package for flash

### ISSUE THREAD

**Issue by onedr0p** [hypriot/flash#173]
The install instructions are pretty easy, but it would be nice to have a homebrew  package for updating.

**Comment by onedr0p** [comment]
If it's helpful, this is how it is done for kubetail which is also a bash script

https://github.com/johanhaleby/homebrew-kubetail

**Comment by StefanScherer** [comment]
Thanks for the suggestion. 
There is a pull request https://github.com/Homebrew/homebrew-core/pull/52503 which you can follow.

**Comment by witsch** [comment]
Unfortunately, getting the pull request (or rather the required test) to be in an acceptable form turned out to be a bit tricky.  Now it should be okay, but it might take another bit for the maintainers to get back to it… 🙂

**Comment by onedr0p** [comment]
No worries, the homebrew maintainers are super stingy on most everything. There's always the way I listed above if they don't approve it. :)

**Comment by StefanScherer** [comment]
It just landed, thanks @witsch !!! 🎉🎉  I couldn't believe this was possible 😅 

<img width="1132" alt="brew-install-flash" src="https://user-images.githubusercontent.com/207759/79461033-e988e780-7ff5-11ea-8ff5-5c8bc67dcc2d.png">

**Comment by witsch** [comment]
You're welcome, I'm glad I could contribute a little bit… and hey, now it's only [one step](https://github.com/witsch/stacks/commit/385ec91f) to get a new Pi running!  Well, almost… 🙂

**Comment by StefanScherer** [comment]
Ping @witsch I don't remember if the homebrew `flash` formula gets updated automatically. I just released version 2.7.1 https://github.com/hypriot/flash/releases/tag/2.7.1 🤗

**Comment by witsch** [comment]
Pong 🙂

They're not, but updating has become very convenient by now. So in this case — and this is mostly meant as a 'note to self' — all that's needed to create https://github.com/Homebrew/homebrew-core/pull/55634 was:
```bash
$ brew bump-formula-pr --url https://github.com/hypriot/flash/releases/download/2.7.1/flash --sha256 …
```

**Comment by StefanScherer** [comment]
Thank you @witsch !
This already creates the PR in homebrew-core?

Do you know if I can run this on Linux here in our pipeline? -> https://github.com/hypriot/flash/blob/master/.circleci/config.yml#L55

**Comment by witsch** [comment]
Yes, it does. I'm not sure how easily it integrates in CI, though. It needs your Github credentials, of course, but then again perhaps all you need is a token in the environment? Would you let me know if you get it to work, please? 🙂
