### ISSUE TITLE
Question: install a web browser

### ISSUE THREAD

**Issue by joeblew99** [hypriot/flash#36]
My use case is running docker and a web browser on each raspberry.

Is this possible ?

**Comment by StefanScherer** [comment]
@joeblew99 Thanks for your feedback. We are working on a tool `device-init` which is the successor of using `occi` to do some firstboot steps. The `flash` script will work together with `device-init` to write a cofnguration file to the FAT partition of the SD card for firstboot customizations.

Please file an issue in https://github.com/hypriot/device-init with suggestions/wishes/etc ;-)
