### ISSUE TITLE
When installing the Flash tool. parse error near `)'

### ISSUE THREAD

**Issue by pascalandy** [hypriot/flash#43]
When I run this command:
`wget https://raw.githubusercontent.com/hypriot/flash/master/$(uname -s)/flash`

I receive this error:
> zsh: parse error near `)'

I don't get it!? 

Brew is freshly installed.

Thank in advance :)

**Comment by StefanScherer** [comment]
Just tried it with bash and zsh, worked in both.

The `uname -s` just returns `Darwin`, so try this

```
wget https://raw.githubusercontent.com/hypriot/flash/master/Darwin/flash
```

Have fun with your cluster ;-)

**Comment by pascalandy** [comment]
Correct in need to use Darwin :)

`wget https://raw.githubusercontent.com/hypriot/flash/master/Darwin/flash`

Thanks!
