### ISSUE TITLE
OSX: when gnu-sed is installed, it doesn't work

### ISSUE THREAD

**Issue by jwhitcraft** [hypriot/flash#48]
On the osx version when gnu-sed is installed, it breaks, it should be hard coded to /usr/bin/sed

Thanks,

**Comment by StefanScherer** [comment]
@jwhitcraft Please download this flash script https://raw.githubusercontent.com/hypriot/flash/use-sed-with-abs-path/Darwin/flash from pull request #49. If this works for you I can merge the PR.

**Comment by searsaw** [comment]
I just had this same issue. Had an issue with `dd` as well (documented in #174). I "fixed" this by updating my PATH so the Mac version were first. Odd that the GNU versions don't work though.

```shell
export PATH="/bin:/usr/bin:$PATH"
111
