### ISSUE TITLE
Change script name to hypriot-flash

### ISSUE THREAD

**Issue by fxstein** [hypriot/flash#56]
Considering broader deployment options like home-brew as in #55 , it might be a good idea to rename the script from `flash` to `hypriot-flash` to avoid current and future naming conflicts.

**Comment by RnbWd** [comment]
but there are no naming conflicts haha (flash is dead)

**Comment by fxstein** [comment]
Call me paranoid. `flash` is a very common term, and its very specific to `hypriot`. as simple `hy` prefix would do. If not I can live with that as well, just a suggestion.

**Comment by RnbWd** [comment]
np I'm just joking around :stuck_out_tongue_winking_eye: --- There's a cask and a science tap named flash - but nothing in the official repo. I like `hy` - anything shorter than `hypriot`. I always misspell the name and I use flash for all raspi images, I think the library's unique and deserves an awesome namespace. But it doesn't really matter - I'd alias it anyway.

**Comment by fxstein** [comment]
Anyway its really up to @StefanScherer and his team to consider. As I said just an opinion.

**Comment by StefanScherer** [comment]
Let's keep the name short. Closing.

**Comment by witsch** [comment]
Fwiw, I've created https://github.com/Homebrew/homebrew-core/pull/52503 to hopefully soon be able to run `brew install flash`.  Let's hope the name will be acceptable for the homebrew maintainers… 🙂

**Comment by StefanScherer** [comment]
It just landed, thanks @witsch !!! 🎉🎉  I couldn't believe this was possible 😅 

<img width="1132" alt="brew-install-flash" src="https://user-images.githubusercontent.com/207759/79461214-25bc4800-7ff6-11ea-91a9-960378cfdd93.png">
