### ISSUE TITLE
Question: change hostname of Raspbian image

### ISSUE THREAD

**Issue by coenroest** [hypriot/flash#63]
Very useful tool to flash images to SD cards, great work!

Is it also possible to change the hostname of a raspbian image or is that only possible with a Hypriot image?

**Comment by StefanScherer** [comment]
@coenroest The flash tool supports the /boot/occidentalis.txt from [Adafruit](https://learn.adafruit.com/adafruit-raspberry-pi-educational-linux-distro/occidentalis-v0-dot-3) and our improved [device-init](https://github.com/hypriot/device-init) tool. But a standard Raspbian SD image does not have any of these tools preinstalled.

So you cannot set the hostname while flashing the SD card.
