### ISSUE TITLE
Suggestion: simplify Mac instructions for flash download (it doesn't need wget)

### ISSUE THREAD

**Issue by martinbartos** [hypriot/flash#72]
Since brew implies bringing it's own particular complications and it's possible to have broken brew installations [I've been struggling with mine which resists all simple repair] 

...and since your script appears to use curl, why not simplify the instructions for download of the flash script and remove the reference to brew altogether..?

`curl -O https://raw.githubusercontent.com/hypriot/flash/master/$(uname -s)/flash
chmod +x flash`

**Comment by StefanScherer** [comment]
@martinbartos Thanks. Good suggestion. Do you want to send us a PR with the corrected README.md? :-)
