### ISSUE TITLE
Please provide option to bypass "are you sure" question to allow scripting.

### ISSUE THREAD

**Issue by medined** [hypriot/flash#73]

**Comment by StefanScherer** [comment]
Good news, but it took a while :-)
I've added an option `-f` to force flashing without the "are you sure" question in #111.

**Comment by StefanScherer** [comment]
Resolved with https://github.com/hypriot/flash/commit/fe090df715ecd0f1260e8c30c69c28fd2eec4478, you can use `-f` to force your decision without a prompt.
