### ISSUE TITLE
Cannot mount partitions after dd on Linux so customizing config files fails

### ISSUE THREAD

**Issue by davidjmurray** [hypriot/flash#76]
On:
Linux Mint 17.1

As the image file actually contains data for 2 partitions, after writing to the SD card using dd, Linux does not know that the partition table may have changed.

This can be fixed by using hdparm to re-read the partition table on the SD card.

So, after the dd (or udevadm settle) and before the mount and file write processes, insert:

hdparm -z "${disk}"

Cheers,

**Comment by StefanScherer** [comment]
@davidjmurray Thanks for your suggestions, also in #75. Could you help me and send a PR with the changes? Thanks!

**Comment by sensorii** [comment]
I've confirmed the bug and the fix.

**Comment by StefanScherer** [comment]
Thanks @sensorii, PR #82 merged.
