### ISSUE TITLE
permission error after  waiting for device...

### ISSUE THREAD

**Issue by dkebler** [hypriot/flash#89]
Flash wrote out the image ok despite the error and I booted right up!....

this permission error appears awhile after the waiting for device.. echo

not sure what flash is doing at that point but obviously not critical to getting a usable card.

using on ubunutu 14.04.

![screenshot from flash](https://cloud.githubusercontent.com/assets/1316185/19296659/30f29276-8ff2-11e6-9da7-6d365b60c67a.png)

**Comment by MathiasRenner** [comment]
I can confirm this error, same for me! (Ubuntu 16.04.1)
It happens for me with any adapter (USB -> MicroSD or Standard SD card adapter)
Thereby, the write protection is disabled of course.

**Comment by StefanScherer** [comment]
Maybe fixed with #106, I tried the latest version in a Linux VM and can't see an error.
Closing this now. Feel free to re-open if the problem still exists on your machine with the latest Linux/flash script.
